name: Lint Code Base

on: [pull_request]

jobs:
  build:
    name: GitHub Super Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter@v4
        env:
          # VALIDATE_EDITORCONFIG: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
